version: '3.8'

services:
  frontend:
    image: paoluhm65/appfilmes_frontend:1.2
    ports:
      - "4200:80"
    container_name: appfilmes_frontend
    depends_on:
      - backend

  backend:
    image: paoluhm65/appfilmes_backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    container_name: appfilmes_backend
    env_file:
      - .env
